services:
  app:
    build:
      context: .  # 使用当前目录作为构建上下文
    container_name: ATRI-LK  # 自定义容器名称
    working_dir: /app  # 容器内工作目录
    ports:
      - "20000:20000"  # 映射端口
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
      - ./res:/app/res
      - ./.env.prod:/app/.env.prod
      - ./config.yml:/app/config.yml
      - ./nonebot_plugins.json:/app/nonebot_plugins.json
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    restart: unless-stopped  # 自动重启策略