[tool.poetry]
name = "ATRI-LK"
version = "1.0.0"
description = "An another project for ATRI, Usage Nonebot2."
authors = ["lokyoh <2366360924@qq.com>"]
license = "GPLv3"
readme = "README.md"
homepage = "https://lokyoh.github.io/ATRI-LK-docs/"
repository = "https://github.com/lokyoh/ATRI-LK"
documentation = "https://lokyoh.github.io/ATRI-LK-docs/"

[tool.poetry.dependencies]
python = "^3.12"
nonebot2 = {extras = ["fastapi"], version = "^2.5.0"}
nonebot-adapter-onebot = "^2.4.6"
edge-tts = "^6.1.19"
tortoise-orm = "^0.21.7"
httpx = "^0.28.1"
scikit-image = "^0.24.0"
apscheduler = "^3.11.0"
rich = "^13.9.4"
tabulate = "^0.9.0"
xmltodict = "^0.13.0"
jieba = "^0.42.1"
psutil = "^6.1.1"
onnxruntime = "^1.22.1"
jinja2 = "^3.1.6"
playwright = "^1.53.0"
aiofiles = "^24.1.0"
markdown = "^3.7"
pymdown-extensions = "^10.16.1"
python-markdown-math = "^0.9"
python-jose = "^3.5.0"
python-multipart = "^0.0.22"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
